Refactoring yaml-script. Testing with error

diff --git a/.github/workflows/initramfs.yml b/.github/workflows/initramfs.yml
--- a/.github/workflows/initramfs.yml
+++ b/.github/workflows/initramfs.yml
@@ -6,11 +6,17 @@ on:
       tag_name:
         description: 'Имя тега для релиза'
         required: true
-        default: 'v24.10.5-custom'
+        default: 'v24.10.5-build'
 
   push:
     tags:
-      - 'v*-build' # Сработает при git push origin v1.2.3
+      - 'v*-build' # Сработает при git push origin v1.2.3-build
+
+env:
+  BUILD_DATA_NAME: ".build_data"
+  PACKAGES_LIST_NAME: "packages.txt"
+  TARGET_CONFIG_NAME: "target.config"
+  MTD_RS_SCRIPT_NAME: "mtd_rs.sh"
 
 
 jobs:
@@ -45,27 +51,47 @@ jobs:
           ./scripts/feeds update -a
           ./scripts/feeds install -a
 
+      - name: Validate paths and files
+        run: |
+          # Формируем полные пути на основе $GITHUB_WORKSPACE
+          BUILD_DATA="$GITHUB_WORKSPACE/${{ env.BUILD_DATA_NAME }}"
+          PACKAGES_LIST="$BUILD_DATA/${{ env.PACKAGES_LIST_NAME }}"
+          TARGET_CONFIG="$BUILD_DATA/${{ env.TARGET_CONFIG_NAME }}"
+          MTD_RS_SCRIPT="$BUILD_DATA/${{ env.MTD_RS_SCRIPT_NAME }}"
+
+
+          # Проверка существования каталога
+          if [ ! -d "$BUILD_DATA" ]; then
+            echo "Error: Directory $BUILD_DATA does not exist."
+            exit 1
+          fi
+
+          if [ ! -f "$TARGET_CONFIG" ]; then
+            echo "Error: Directory $TARGET_CONFIG does not exist."
+            exit 1
+          fi
+
+          if [ ! -d "$MTD_RS_SCRIPT" ]; then
+            echo "Error: Directory $MTD_RS_SCRIPT does not exist."
+            exit 1
+          fi
+
+
       - name: Configure Firmware
         run: |
           cd openwrt
 
           # 1. Применяем конфиг железа (target.config)
-          if [ -f "$GITHUB_WORKSPACE/.build_data/target.config" ]; then
-            sed -e 's/#.*//' -e '/^$/d' "$GITHUB_WORKSPACE/.build_data/target.config" >> .config
-          fi
+            sed -e 's/#.*//' -e '/^$/d' "$TARGET_CONFIG" >> .config
 
           # 2. Добавляем пакеты (packages.txt)
-          if [ -f "$GITHUB_WORKSPACE/.build_data/packages.txt" ]; then
-            sed -e 's/#.*//' -e 's/^-.*//' -e '/^$/d' "$GITHUB_WORKSPACE/build_data/packages.txt" | sort -u | while read -r pkg; do
+            sed -e 's/#.*//' -e 's/^-.*//' -e '/^$/d' "$PACKAGES_LIST" | sort -u | while read -r pkg; do
               echo "CONFIG_PACKAGE_$pkg=y" >> .config
             done
-          fi
 
           # 3. Копируем внешний скрипт в структуру образа
-          if [ -f "$GITHUB_WORKSPACE/.build_date/files/etc/scripts/mtd-rs.sh" ]; then
             mkdir -p files/etc/scripts
-            cp "$GITHUB_WORKSPACE/.build_date/files/etc/scripts/mtd-rs.sh" files/etc/scripts/mtd-rs.sh
-          fi
+            cp "$MTD_RS_SCRIPT" files/etc/scripts/mtd-rs.sh
 
           make defconfig
 
@@ -88,6 +114,21 @@ jobs:
           cp openwrt/.config bin_out/build.config
           cp $GITHUB_WORKSPACE/.build_date/packages.txt bin_out/installed_packages.txt || touch bin_out/installed_packages.txt
           cd bin_out && sha256sum *.itb > sha256sums.txt || true
+
+      - name: Prepare Artifacts and Checksums
+        run: |
+          # Путь к папке с результатами сборки
+          OUTPUT_DIR="openwrt/bin/targets/mediatek/filogic"
+
+          # Копируем конфиги для истории в релиз
+          cp "$TARGET_CONFIG" "$OUTPUT_DIR/user.config"
+          cp "$PACKAGES_LIST" "$OUTPUT_DIR/user_packages.txt"
+
+          cd "$OUTPUT_DIR"
+          rm -f sha256sums
+          sha256sum * > sha256sums
+
+
 
 #     - name: Delete Old Releases
 #       if: success()
@@ -115,9 +156,7 @@ jobs:
         with:
           tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
           files: |
-            openwrt/bin/targets/mediatek/filogic/*-initramfs.itb
-            openwrt/bin/targets/mediatek/filogic/config.buildinfo
-            openwrt/bin/targets/mediatek/filogic/sha256sums
+            openwrt/bin/targets/mediatek/filogic/*
           generate_release_notes: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
